### ISSUE TITLE
Create Rope Project fails with "ImportError: No module named rope.base.project"

### ISSUE THREAD

**Issue by pbx** [dnatag/PyRefactor#9]
Sublime Text 3, build 3103, Linux.

Latest rope installed in the global Python site-packages via pip.

Did I miss some setup instructions?

**Comment by igoose1** [comment]
```bash
pip install rope
```
or
```bash
python -m pip install rope
```
using python2.7 helped me.

I think you tried to install package via pip3 (python3) too.

**Comment by pbx** [comment]
Old issue with a satisfactory reply. Closing.
